### ISSUE TITLE
pmod namespace - capital letters

### ISSUE THREAD

**Issue by mhsano** [pybel/pybel#123]
Hi,

We get exceptions if there are statements witth protein modifications starting with a capital letter (e.g. proteinModification(Phosphorylation).

Is it possible to make this case-insensitive?

Thanks,
manfred

**Comment by cthoyt** [comment]
Technically this isn't valid under the BEL specification. See: http://openbel.org/language/web/version_2.0/bel_specification_version_2.0.html#_modification_types_provided_in_default_bel_namespace

We've toyed with the idea of throwing out case entirely, but also see the value in enforcing controlled vocabularies. For example, the words Polish and polish are not the same. In biology, this is also a problem when referring to Mouse genes versus Human genes.

**Comment by cthoyt** [comment]
Manfred,

I hope you've figured out a solution to this problem. I would suggest using either a text-editor with a find-replace functionality if this issue is isolated to one BEL Script, or writing a bash script that scans for all of your BEL files and runs a simple sed command to find and replace this text. This page seems like it has a cookie-cutter solution: http://askubuntu.com/questions/20414/find-and-replace-text-within-a-file-using-commands

**Comment by mhsano** [comment]
We have converted all modifications to lower case....


Thanks.
