### ISSUE TITLE
List annotation definitions now failing

### ISSUE THREAD

**Issue by dexterpratt** [pybel/pybel#180]
worked correctly in earlier version. Now fails to create valid CX from pybel_test.bel

Noticed this because of serialization failure for list annotation definitions, but on inspecting the @context, it looks like some PyBEL data structure is now being used directly instead of being transformed into the @context form.

**Comment by cthoyt** [comment]
You're right. I realized I forgot to output all of the definitions, and updated this part of the serialization. I can easily fix the problem with the list annotation. They're internally stored as a set, and just need to be cast to a sorted list before output.

But is it also a problem the structure that I'm using now, compared to the previous structure, which was just a dictionary of {keyword: url}? The reason I changed it was so that I could tell which OWL documents were supposed to be annotations or namespaces, since they don't have different file extensions, and to also include the list annotations

**Comment by dexterpratt** [comment]
Yup, the CX specification defines that schema for @context. 

Although removing the line that caused the serialization error allowed me to upload the resulting CX, it then failed validation testing on the server.

@context was adopted from JSONLD.  CX is intended to be JSONLD compliant where possible.

**Comment by cthoyt** [comment]
Okay this has finally been closed and merged into master (we're having some problems with testing on Travis CI because some of our tests are **very** slow)

Reference: a60790b940992a24091a0595ba38d23fce79ad0b
