### ISSUE TITLE
Name conflict with Open Babel's Pybel

### ISSUE THREAD

**Issue by baoilleach** [pybel/pybel#217]
Hi there, I'm a developer of Open Babel and the author of its Python interface, also called Pybel. This has been around for a while - e.g. a paper back in 2008, "Pybel: a Python wrapper for the OpenBabel cheminformatics toolkit" (https://doi.org/10.1186/1752-153X-2-5).

We're starting to get support requests regarding confusion over "pip install pybel". We have "pip install openbabel" instead, which installs a pybel.py and openbabel.py. You can see where the confusion arises.

We can do a certain amount at our end to avoid the technical problem of a pybel.py versus a pybel directory, but we would appreciate if you would consider renaming your project to make it easier for users to find the software they are looking for and to avoid confusion.

**Comment by cthoyt** [comment]
I've searched the internet for solutions to installing multiple packages with the same name, but haven't found anything good. It's not a very common problem in the Python community since the standard is for packages to have the same name on PyPI as the name under which they install.

I've read your paper and documentation and it seems to me like `pybel` is a subordinate of `openbabel`. In other large software ecosystems like `sqlalchemy`, subordinate packages that are standard get installed to `sqlalchemy.ext.contrib`. Alternatively, `flask` took a different approach (which we also took with extensions to our `pybel`) where extensions are named `flask_admin` and so on. 

If I were to use your package (and after looking through it I will be searching for an opportunity to do so!) then I think I might also be confused as to why there is another package imported in examples, and then try to install `pybel` from pip myself. A solution might be to change your setup.py to install the current `pybel` to something like `openbabel_pybel` or even better, restructure your project so `pybel` is a subpackage of `openbabel` and can be imported as `openbabel.pybel`. This would make it 100% explicit (and Tim Peters would be proud)

In the mean time, we can post a notice on the readme for our package with a link to your installation documentation and a short explanation of the problem for any users who are confused. I hope this is agreeable for now.

**Comment by baoilleach** [comment]
I agree, and we are planning to move to "from openbabel import pybel". This was what I was referring to regarding fixing the technical problem.

The issue of the name conflict still exists, though, for people googling for information/tutorials/etc. I guess you're saying that's a "Wont Fix", but I thought I would try.

**Comment by cthoyt** [comment]
Since you're already restructuring your project, I would go as far as to recommend you rename your `pybel` to `pyopenbabel`, or even eliminate this hierarchy completely. I would expect from all modern packages the pythonic features in `pybel` to be built in by default.
