### ISSUE TITLE
Errors processing CausalBioNet JGF files

### ISSUE THREAD

**Issue by johnbachman** [pybel/pybel#266]
I get the following error when I attempt to process the file `Wnt-2.0-Hs.jgf` in the `Human-2.0` collection of JGF downloads:

```
In [8]: pb = pybel.from_cbn_jgif(wnt)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-8-fd94c42231a9> in <module>()
----> 1 pb = pybel.from_cbn_jgif(wnt)

~/Dropbox/1johndata/Knowledge File/Biology/Research/Big Mechanism/pybel/src/pybel/io/jgif.py in from_cbn_jgif(graph_jgif_dict)
    133     >>> graph = from_cbn_jgif(graph_jgif_dict)
    134     """
--> 135     graph_jgif_dict = map_cbn(graph_jgif_dict)
    136 
    137     graph_jgif_dict['graph']['metadata'].update({

~/Dropbox/1johndata/Knowledge File/Biology/Research/Big Mechanism/pybel/src/pybel/io/jgif.py in map_cbn(d)
     82 
     83             for key, value in evidence[EXPERIMENT_CONTEXT].items():
---> 84                 value = value.strip()
     85 
     86                 if not value:

AttributeError: 'NoneType' object has no attribute 'strip'

In [9]: debug
> /Users/johnbachman/Dropbox/1johndata/Knowledge File/Biology/Research/Big Mechanism/pybel/src/pybel/io/jgif.py(84)map_cbn()
     82 
     83             for key, value in evidence[EXPERIMENT_CONTEXT].items():
---> 84                 value = value.strip()
     85 
     86                 if not value:

ipdb> key
'disease'
ipdb> value
ipdb> 
```

**Comment by johnbachman** [comment]
Here's an error when attempting to process `Apoptosis-2.0-Hs.jgf`:

```
~/Dropbox/1johndata/Knowledge File/Biology/Research/Big Mechanism/pybel/src/pybel/parser/parse_identifier.py in handle_namespace_invalid(self, line, position, tokens)
    144     def handle_namespace_invalid(self, line, position, tokens):
    145         name = tokens[NAME]
--> 146         raise NakedNameWarning(self.line_number, line, position, name)

NakedNameWarning: [pos:2] "CXCL12" should be qualified with a valid namespace
```

**Comment by johnbachman** [comment]
I did a quick pass over the files and separated them into files that were successfully parsed by `pybel.from_cbn_jgif` and not:

Success:
```
Angiogenesis-2.0-Hs.jgf
Cell Cycle-2.0-Hs.jgf
Clock-2.0-Hs.jgf
Cytotoxic T-cell Signaling-2.0-Hs.jgf
Dendritic Cell Signaling-2.0-Hs.jgf
Endothelial Innate Immune Activation-2.0-Hs.jgf
Epigenetics-2.0-Hs.jgf
Hox-2.0-Hs.jgf
Jak Stat-2.0-Hs.jgf
Mapk-2.0-Hs.jgf
Mast cell activation-2.0-Hs.jgf
Megakaryocyte Differentiation-2.0-Hs.jgf
mTor-2.0-Hs.jgf
NFE2L2 Signaling-2.0-Hs.jgf
NK Signaling-2.0-Hs.jgf
Notch-2.0-Hs.jgf
PGE2-2.0-Hs.jgf
Tissue Damage-2.0-Hs.jgf
```

Failure:
```
Apoptosis-2.0-Hs.jgf
Autophagy-2.0-Hs.jgf
B-cell Signaling-2.0-Hs.jgf
Calcium-2.0-Hs.jgf
Cell Interaction-2.0-Hs.jgf
ECM Degradation-2.0-Hs.jgf
Endoplasmic Reticulum Stress-2.0-Hs.jgf
Epithelial Innate Immune Activation-2.0-Hs.jgf
Epithelial Mucus Hypersecretion-2.0-Hs.jgf
Fibrosis-2.0-Hs.jgf
Growth Factor-2.0-Hs.jgf
Hedgehog-2.0-Hs.jgf
Hypoxic Stress-2.0-Hs.jgf
Immune Regulation of Tissue Repair-2.0-Hs.jgf
Macrophage Signaling-2.0-Hs.jgf
Necroptosis-2.0-Hs.jgf
Neutrophil Signaling-2.0-Hs.jgf
Nuclear Receptors-2.0-Hs.jgf
Osmotic Stress-2.0-Hs.jgf
Oxidative Stress-2.0-Hs.jgf
Response to DNA Damage-2.0-Hs.jgf
Senescence-2.0-Hs.jgf
Th1-Th2 Signaling-2.0-Hs.jgf
Th17 Signaling-2.0-Hs.jgf
Treg Signaling-2.0-Hs.jgf
Wnt-2.0-Hs.jgf
Wound Healing-2.0-Hs.jgf
Xenobiotic Metabolism Response-2.0-Hs.jgf
```

**Comment by cthoyt** [comment]
Fantastic! I will try and make some updates, but I'm still under the impression that the CBN data doesn't always conform to BEL or JGIF standards...

**Comment by kkaris** [comment]
We have recently made an effort to try to include CBN jgif files to the indra database. We're using [`from_cbn_jgif` in `pybel/io/jgif.py`](https://github.com/pybel/pybel/blob/0ff0effa87725f6e4f4f0a74083afe23af89b37b/src/pybel/io/jgif.py#L127) to get the pybel graph as an intermediate before making statements. The process does at least pass through the pipeline and produce statements, but there are some warnings of unhandled annotations, for example:
```
WARNING: [2019-03-11 15:50:27] indra.sources.bel.processor - unhandled annotation: Cell:Endothelial Cells
WARNING: [2019-03-11 15:50:27] indra.sources.bel.processor - unhandled annotation: Cell:neuron
WARNING: [2019-03-11 15:50:27] indra.sources.bel.processor - unhandled annotation: Cell:leukocyte
WARNING: [2019-03-11 15:50:27] indra.sources.bel.processor - unhandled annotation: Cell:Myocytes, Smooth Muscle
WARNING: [2019-03-11 15:50:27] indra.sources.bel.processor - unhandled annotation: Cell:Macrophages
```
I believe the warnings are [warned](https://github.com/pybel/pybel/blob/0ff0effa87725f6e4f4f0a74083afe23af89b37b/src/pybel/io/jgif.py#L144) about (pun intended) in the docs already, but I was wondering if there are any plans to handle the unhandled annotations?

**Comment by cthoyt** [comment]
I didn't have any plans to revisit this, but two options might be:

1. Make updates to the source content to ensure semantic integrity. I was asked by PMI to support them in reclaiming the JGIF content, since somehow the originals have gone missing. Making updates to our own copies of the content isn't such a good idea either, because then it would be out of sync with the source and become a problem if CBN ever makes an update.

2. Try and normalize the content after it is read from JGIF. This is out of the scope of PyBEL, and if we wanted to do something like this, I would completely excise `pybel.io.jgif` into a separate package that could also include tools for normalization. This would need to come after processing the BEL with PyBEL but before using `indra.sources.bel.api.process_pybel_graph()` and just check each one to make sure that it actually is labeled with the correct annotation (then again, I just looked up Cell:leukocyte and the OLS said it's actually correct, so maybe we also need to update these errors to be a bit more helpful... It's probably my fault that they're so vague)

I think what happened in a lot of these cases is the curators mixed up using the *Cell* annotation, which is supposed to come from the Cell Ontology, *CellLine*, which is a combination of subsets of the Cell Line Ontology and Experimental Factor Ontology, and also the wild mixture of MeSH annotation files that Selventa originally made. 

P.S. Pun appreciated

**Comment by kkaris** [comment]
Thanks for the comments! We're airing on accepting the indra statements as they come out for the time being.
