### ISSUE TITLE
pybel.from_biopax returns an empty graph.

### ISSUE THREAD

**Issue by ghost** [pybel/pybel#323]
Hello everyone,

I am trying to convert [KGML](https://www.kegg.jp/kegg/xml/) into BEL. I have translated KGMLs into the BioPax format (level 3) using the [KEGGtranslator](http://www.cogsys.cs.uni-tuebingen.de/software/KEGGtranslator/) tool. Howerver when I finally load it using pybel I get an empty graph.

```
import pybel
graph = pybel.from_biopax('hsa04060.translated')

pybel.to_json(graph)      # returns empty JSON graph
(graph.number_of_nodes()  # returns 0
```

[hsa04060.translated](https://gist.github.com/ejlima/8da9377fa34d44940695e02b666ca585)
[output](https://gist.github.com/ejlima/732de29090abc7767b622e04df7180d5)

**Comment by cthoyt** [comment]
Hi @ejlima, thanks for checking in on this. 

The [PyBEL BioPAX importer](http://pybel.readthedocs.io/en/latest/_modules/pybel/io/indra.html#from_biopax) is heavily built on the [INDRA BioPAX processor](https://indra.readthedocs.io/en/latest/modules/sources/biopax/index.html?highlight=process_owl#indra.sources.biopax.biopax_api.process_owl). I've linked both of their documentation here.

I've also had a couple issues with this before, and they're likely due to the heterogeneity of BioPAX. I would also send this question to @bgyori and @johnbachman (maintainiers of INDRA)

Working on converters between these formats is also ongoing work for one of @ddomingof's masters students. She's not on GitHub yet but we'll get her involved in this conversation too.

**Comment by ejlima** [comment]
@cthoyt Thank you for your quick reply!

If translating from KEGG into BEL through BioPax is not possible, do you have a reccomended way to achieve this?

**Comment by ddomingof** [comment]
Hi @ejlima, we are working on a direct translator from KGML into BEL (with PyBEL). We have not finished this project yet, but it is currently in an advance status and will be ready by the end of the next month (due to holidays =)). Once it is ready to be published here, we will be happy to share the code with you. 

If you have interest and want to contribute contact us privatly via email.

**Comment by cthoyt** [comment]
Btw my work email is listed on my github profile page (@cthoyt) :)

**Comment by evertonjlima** [comment]
Are there any new updates about the tool? 

Thank you.

**Comment by cthoyt** [comment]
CC: @10mubeen

**Comment by remondulos** [comment]
I am also interested in using this tool, is there any update on this development?

**Comment by 10mubeen** [comment]
Hi @evertonjlima @remondulos, we're currently working on the translator. It should be ready very soon (in the next couple of weeks or so). We'll keep you posted!

**Comment by cthoyt** [comment]
Update for @evertonjlima @remondulos - please check https://github.com/compath/pathme. It's still in the works, but it pretty successfully gets KEGG as BEL. Your feedback on usability would be appreciated - it might not be the easiest to figure out at the moment :)

If there are any issues, we could send you a dump of all of them (I think that's legally okay, but KEGG is quite tricky when it comes to sharing...)

@ddomingof could you update the documentation tomorrow to show how the user can get programatica access to the BEL graphs? There should a function in `pathme.kegg` called `get_bel_graphs` that returns a `Dict[str,pybel.BELGraph]` of names to graphs.

**Comment by cthoyt** [comment]
Hi everyone, PathMe is pretty mature at this point. 

It's got plenty of caveats, which Daniel and Sarah discuss in the [documentation](https://pathme.readthedocs.io) and [corresponding manuscript](https://doi.org/10.1101/451625) for PathMe, but overall it's pretty good at getting this content as BEL.

I'm going to close this issue - please feel free to continue conversation here or make new issues on the [PathMe repository](https://github.com/PathwayMerger/PathMe) if there's something specific. Any questions about how to use the software are more than welcome, and we will update the documentation to make sure that any questions are answered in detail
