### ISSUE TITLE
Edges no longer contain hashes (in develop branch)

### ISSUE THREAD

**Issue by johnbachman** [pybel/pybel#331]
I noticed a test in the pybel_processor was failing in INDRA. The error occurs here:

https://github.com/sorgerlab/indra/blob/4c52ed351457fd33e91ef5b1205dd79d0060a60d/indra/tests/test_pybel_api.py#L325

...when checking that the INDRA Evidence object created for the Statement contains a `source_id` attribute equal to the hash of the edge. This is due to the fact that the edge_data dictionary no longer contains the hash attribute, so that this line

https://github.com/sorgerlab/indra/blob/4c52ed351457fd33e91ef5b1205dd79d0060a60d/indra/sources/bel/pybel_processor.py#L476

...ends up setting it to none. This is attributable to commit 5f2070df4b7 in the develop branch, specifically here

https://github.com/pybel/pybel/commit/5f2070df4b765e47bc24a9b7fee7540b387689af#diff-cbcb404f0c0a08a5bceade8d9eb2713dL1068 

and here:

https://github.com/pybel/pybel/commit/5f2070df4b765e47bc24a9b7fee7540b387689af#diff-23545ca0e99fc16f70843c8acdd5bcc6L525

What is the difference in role between the `key` and the hash? For the evidence `source_id` we'd be looking for a unique identifier that could be used to back-trace the INDRA Statement back to the edge in the PyBEL graph. Which is more appropriate for that, the `key` or the hash?

**Comment by cthoyt** [comment]
Before, the keys in the multidigraph were mostly haphazard. Now, I just use the same hash as the keys! This makes it way easier to check for existence of an edge in the graph already, too. This was necessary for the process of upgrading NetworkX to 2.1+, too. I'm still working towards that (all of the code that was living in PyBEL Tools has made its way to PyBEL and is now unit tested, so this might not take so long now)

I can submit a PR to fix this - it shouldn't be so difficult since it would just need an update to the iterator here https://github.com/sorgerlab/indra/blob/4c52ed351457fd33e91ef5b1205dd79d0060a60d/indra/sources/bel/pybel_processor.py#L69 to include the `keys=True` then pass that along to all of the functions that are calling it

**Comment by johnbachman** [comment]
A PR would be awesome, thanks!
