### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 8815866: character maps to <undefined>

### ISSUE THREAD

**Issue by Rajeswara-Rao** [pybel/pybel#473]
Hello,

I am trying to plot a graph from BioPAX file. 

While I am executing below code I got an error 'UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 8815866: character maps to <undefined>' in last line.

```python
url = 'https://reactome.org/ReactomeRESTfulAPI/RESTfulWS/biopaxExporter/Level2/1643685'
path = os.path.join(os.path.expanduser('~'), 'Downloads', 'WP254_951071.owl')
if not os.path.exists(path):
    urlretrieve(url, apoptosis_path)
graph = pybel.from_biopax(apoptosis_path)
```

Please help me to resolve it.

**Comment by cthoyt** [comment]
Hi! Could you please paste the entire stack trace, as well as the version of python, pybel, and Indra that you're using?

If I had to guess without seeing that, it would be that the biopax file is using a nonstandard (ie not utf8) encoding.

**Comment by Rajeswara-Rao** [comment]
Hello, Thanks for your quick  reply

I am using python 3.8.3,pybel 0.14.1 and indra 1.18.0

import os
import pybel
from urllib.request import urlretrieve
apoptosis_url = 'https://reactome.org/ReactomeRESTfulAPI/RESTfulWS/biopaxExporter/Level2/1643685'
apoptosis_path = os.path.join(os.path.expanduser('~'), 'Downloads', 'WP254_951071.owl')
if not os.path.exists(apoptosis_path):
    urlretrieve(apoptosis_url, apoptosis_path)
graph = pybel.from_biopax(apoptosis_path)

UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-2-521428bb8621> in <module>
----> 1 graph = pybel.from_biopax(apoptosis_path)

~\Anaconda3\lib\site-packages\pybel\io\indra.py in from_biopax(path, name, version, description, authors, contact, license, copyright, disclaimer)
    167     from indra.sources.biopax import process_owl
    168 
--> 169     model = process_owl(path)
    170 
    171     return from_indra_statements(

~\Anaconda3\lib\site-packages\indra\sources\biopax\api.py in process_owl(owl_filename)
    171         A BiopaxProcessor containing the obtained BioPAX model in bp.model.
    172     """
--> 173     model = model_from_owl_file(owl_filename)
    174     return process_model(model)
    175 

~\Anaconda3\lib\site-packages\pybiopax\api.py in model_from_owl_file(fname)
     39     """
     40     with open(fname, 'r') as fh:
---> 41         owl_str = fh.read()
     42         return model_from_owl_str(owl_str)
     43 

~\Anaconda3\lib\encodings\cp1252.py in decode(self, input, final)
     21 class IncrementalDecoder(codecs.IncrementalDecoder):
     22     def decode(self, input, final=False):
---> 23         return codecs.charmap_decode(input,self.errors,decoding_table)[0]
     24 
     25 class StreamWriter(Codec,codecs.StreamWriter):

UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 8815866: character maps to <undefined>

**Comment by cthoyt** [comment]
You'll notice that this error is actually happening in a transitive dependency, PyBioPAX, because PyBEL defers to INDRA's BioPAX reader, and INDRA defers to PyBioPAX.  

It's likely due to an issue with the default encoding (ref: https://stackoverflow.com/questions/9233027/unicodedecodeerror-charmap-codec-cant-decode-byte-x-in-position-y-character). Are you on Windows?

I've made a PR to PyBioPAX at https://github.com/indralab/pybiopax/pull/7 that will be the first step in fixing the issue. After that's accepted, we can make a PR on INDRA, then updated PyBEL. 

Because PyBEL is just wrapping the INDRA code for convenience, I'll provide you with an example that re-implements some of this for immediate use.

```python
import os
import pybel
import indra.sources.biopax
import pybiopax
from urllib.request import urlretrieve
apoptosis_url = 'https://reactome.org/ReactomeRESTfulAPI/RESTfulWS/biopaxExporter/Level2/1643685'
apoptosis_path = os.path.join(os.path.expanduser('~'), 'Downloads', 'WP254_951071.owl')
if not os.path.exists(apoptosis_path):
    urlretrieve(apoptosis_url, apoptosis_path)

with open(apoptosis_path, 'r', encoding='utf-8') as file:
    owl_str = file.read()
    biopax_model = pybiopax.model_from_owl_str(owl_str)

biopax_processor = indra.sources.biopax.process_model(biopax_model)

graph = pybel.from_indra_statements(biopax_processor.statements)
```

If it fails on the file reading, try some different encodings until you get success.

**Comment by Rajeswara-Rao** [comment]
Thanks for your support!!

The error has resolved now.

**Comment by cthoyt** [comment]
Great! We're working on updating our first-class WikiPathways -> BEL converter which needs a bit of maintenance, and I'm sure it will get better results than the WikiPathways -> Reactome -> INDRA -> BEL loop here once it's ready. Until then, happy coding!

**Comment by Rajeswara-Rao** [comment]
Hello @cthoyt , I was trying to plot a graph using PyBEL after reading a BioPAX file. 
I am getting an empty graph by using below code

```
import os
from urllib.request import urlretrieve
from pybel_jupyter import to_jupyter
import indra.sources.biopax
import pybel
import pybiopax

apoptosis_url = 'https://reactome.org/ReactomeRESTfulAPI/RESTfulWS/biopaxExporter/Level2/1643685'
apoptosis_path = os.path.join(os.path.expanduser('~'), 'Downloads', 'WP254_951071.owl')
if not os.path.exists(apoptosis_path):
    urlretrieve(apoptosis_url, apoptosis_path)

with open(apoptosis_path, 'r', encoding='utf-8') as file:
    owl_str = file.read()
    biopax_model = pybiopax.model_from_owl_str(owl_str)

biopax_processor = indra.sources.biopax.process_model(biopax_model)
graph = pybel.from_indra_statements(biopax_processor.statements)

to_jupyter(graph)

```

While I am  trying to get summary of graph I am getting as

`graph.summarize()`

indra v64396028-494f-47d8-b3b8-cdfec1102634
Number of Nodes: 0
Number of Edges: 0
Number of Citations: 0
Number of Authors: 0
Network Density: 0.00E+00
Number of Components: 0
Number of Warnings: 0

Please provide me a solution to resolve this problem.
Thanks!

**Comment by cthoyt** [comment]
Unfortunately, problem is not originating from PyBEL, but rather due to the content from Reactome itself. BioPAX is only an upper level ontology and it does not prescribe how information should be encoded. Since Reactome does not use the schema that PyBioPAX expects, PyBioPAX can not parse anything useful from Reactome content. Therefore, no information makes it into INDRA statements via `biopax_processor = indra.sources.biopax.process_model(biopax_model)` and none into the BEL graph via
`graph = pybel.from_indra_statements(biopax_processor.statements)`. 

You can check that this is the case with:

```python
>>> import pybiopax
>>> model = pybiopax.model_from_owl_url('https://reactome.org/ReactomeRESTfulAPI/RESTfulWS/biopaxExporter
>>> len(model.objects)
0
```

You can also do a check that there are no INDRA statements parsed from the empty PyBioPAX model

```python
>>> len(biopax_processor.statements)
0
```

You can see that content returned from Pathway Commons does have useful information, though:

```python
>>> import pybiopax
>>> model = pybiopax.model_from_pc_query('pathsfromto', ['MAP2K1'], ['MAPK1'])
>>> len(model.objects)
13022
```

I would suggest moving questions about BioPAX processing over to the https://github.com/indralab/pybiopax (its maintainer, Ben Gyori, can likely write a better explanation on what's going on with the Reactome content) or to directly contact the Reactome team for support on their BioPAX content

**Comment by cthoyt** [comment]
After looking at the URL, you're using BioPAX level 2. Switch your URL to `https://reactome.org/ReactomeRESTfulAPI/RESTfulWS/biopaxExporter/Level3/1643685` and you get something looking much more useful.

**Comment by Rajeswara-Rao** [comment]
@cthoyt  Thanks for your support !

**Comment by cthoyt** [comment]
@Rajeswara-Rao as of https://github.com/pybel/pybel/commit/820200684e29e69a01b8c6636b9cbbf5f213978b, it should now be possible to directly specify the file encoding from the PyBEL function `pybel.from_biopax` with no need to use the wrapped INDRA or PyBioPAX functions. Your use case can now be more simply written as:

```python
import os
from urllib.request import urlretrieve
from pybel_jupyter import to_jupyter
import pybel

apoptosis_url = 'https://reactome.org/ReactomeRESTfulAPI/RESTfulWS/biopaxExporter/Level3/1643685'
apoptosis_path = os.path.join(os.path.expanduser('~'), 'Downloads', 'WP254_951071.owl')
if not os.path.exists(apoptosis_path):
    urlretrieve(apoptosis_url, apoptosis_path)

graph = pybel.from_biopax(apoptosis_path, encoding='utf-8')

to_jupyter(graph)
```

**Comment by Rajeswara-Rao** [comment]
@cthoyt Thanks for the update!
